on: push

name: Multi

jobs:
  pre-stg-deploy-action:
    runs-on: ubuntu-latest
    steps:
      - name: pre-stg-deploy-action
        run: |
          echo "pre-stg-deploy-action"

  stg-deploy:
    environment: staging
    needs: pre-stg-deploy-action
    runs-on: ubuntu-latest
    steps:
      - name: stg deploy
        run: |
          echo "stg deploy"

  stg2-deploy:
    environment: staging2
    needs: pre-stg-deploy-action
    runs-on: ubuntu-latest
    steps:
      - name: stg2 deploy
        run: |
          echo "stg2 deploy"

  stg3-deploy:
    environment: staging3
    needs: pre-stg-deploy-action
    runs-on: ubuntu-latest
    steps:
      - name: stg3 deploy
        run: |
          echo "stg3 deploy"

  prod-deploy:
    environment: production
    needs: stg-deploy
    runs-on: ubuntu-latest
    steps:
      - name: prod-deploy
        run: |
          echo "prod deploy"
