on: push

name: separate

jobs:
  # 承認なし
  pre-stg-deploy-action:
    runs-on: ubuntu-latest
    steps:
      - name: pre-stg-deploy-action
        run: |
          echo "pre-stg-deploy-action"

  stg-deploy:
    needs: pre-stg-deploy-action
    runs-on: ubuntu-latest
    steps:
      - name: stg deploy
        run: |
          echo "stg deploy"

  # 承認付き
  pre-prod-deploy-action:
    runs-on: ubuntu-latest
    steps:
      - name: pre-prod-deploy-action
        run: |
          echo "pre-prod-deploy-action"

  prod-deploy:
    environment: production
    needs: pre-prod-deploy-action
    runs-on: ubuntu-latest
    steps:
      - name: prod-deploy
        run: |
          echo "prod deploy"
